-- Base de tópicos da plataforma. Gerado por: python -m upq.topicos
insert into public.topicos (disciplina, topico, assuntos) values
('História', 'Idade Antiga', ARRAY['Egito', 'Grécia', 'Primeiras civilizações', 'Roma']::text[]),
('História', 'Idade Média', ARRAY['Cruzadas', 'Feudalismo', 'Império Bizantino']::text[]),
('História', 'Idade Moderna', ARRAY['Estados Nacionais', 'Expansão marítima', 'História da América', 'Mercantilismo', 'Reforma e contrarreforma', 'Renascimento', 'Revolução industrial']::text[]),
('História', 'Idade Contemporânea', ARRAY['Entreguerras', 'Guerra Fria', 'Imperialismo', 'Nazifascismo', 'Primaveira Árabe', 'Primeira Guerra Mundial', 'Revolução Francesa', 'Segunda Guerra Mundial']::text[]),
('História', 'Brasil Colônia', ARRAY['Catequização', 'Ciclos econõmicos', 'Escravidão', 'Independência', 'Revoltas brasileiras']::text[]),
('História', 'Brasil Império', ARRAY['Abolição da escravidão', 'Guerra do Paraguai', 'Período Regencial', 'Primeiro Reinado', 'Revoltas brasileiras', 'Segundo Reinado']::text[]),
('História', 'Brasil República', ARRAY['Constituição Federal', 'Direitos Sociais', 'Ditadura militar', 'Era Vargas', 'Governo JK', 'Proclamação da República', 'Redemocratização', 'República Oligárquica', 'República Velha', 'Revoltas brasileiras']::text[]),
('Geografia', 'Geografia Econômica', ARRAY['Blocos econômicos', 'Comércio', 'Conceitos geográficos', 'Desigualdade socioeconômica', 'DIT', 'Doutrinas econômicas', 'Fontes de energia', 'Globalização', 'Modais', 'Modelos de produção', 'Neoliberalismo', 'Setores da economia', 'Sistemas econômicos']::text[]),
('Geografia', 'Geografia Urbana e Demografia', ARRAY['Densidade demográfica', 'Fenômenos urbanos e problemas sociais', 'Indicadores demográficos', 'Migrações', 'Pirâmides etárias', 'Teorias demográficas', 'Transição demográfica']::text[]),
('Geografia', 'Geografia Agrária', ARRAY['Conflitos no campo', 'Estrutura fundiária', 'Modelos de produção agrícola', 'Reforma agrária', 'Revolução verde']::text[]),
('Geografia', 'Geopolítica', ARRAY['Blocos econômicos', 'Colonialismo e neocolonialismo', 'Conflitos geopolíticos', 'Imperialismo', 'Ordens mundiais', 'Sustentabilidade']::text[]),
('Geografia', 'Geografia Física', ARRAY['Cartografia', 'Ciclo das rochas', 'Eras geológicas', 'Geologia', 'Relevos', 'Tectonismo']::text[]),
('Geografia', 'Hidrografia', ARRAY[]::text[]),
('Geografia', 'Climatologia', ARRAY['Climas do Brasil', 'El Nino e La Nina', 'Fatores do clima', 'Fenômenos climáticos']::text[]),
('Geografia', 'Impactos ambientais', ARRAY['Degradação dos solos', 'Desmatamento', 'Escassez hídrica', 'Mudanças climáticas', 'Poluição']::text[]),
('Filosofia', 'Fundamentos da Filosofia', ARRAY['A Passagem do Mito ao Logos', 'Mito e Religião', 'O Que é Filosofia']::text[]),
('Filosofia', 'Filosofia Clássica', ARRAY['Aristóteles', 'Platão', 'Pré-Socráticos', 'Sócrates']::text[]),
('Filosofia', 'Filosofia Moderna', ARRAY['Contratualismo', 'Idealismo', 'Iluminismo', 'Kant', 'Racionalismo e empirismo']::text[]),
('Filosofia', 'Filosofia Contemporânea', ARRAY['Educação', 'Escola de Frankfurt', 'Guerra Fria', 'Michel Foucault', 'Nietzche', 'Sartre']::text[]),
('Filosofia', 'Filosofia Religiosa', ARRAY['Santo Agostinho', 'São Tomás de Aquino']::text[]),
('Filosofia', 'Filosofia da Ciência', ARRAY[]::text[]),
('Filosofia', 'Ética e Moral', ARRAY[]::text[]),
('Filosofia', 'Política', ARRAY[]::text[]),
('Sociologia', 'Fundamentos da Sociologia', ARRAY['O Que é Sociologia', 'Sociologia e suas Áreas']::text[]),
('Sociologia', 'Sociólogos Clássicos', ARRAY['Auguste Comte', 'Émile Durkheim', 'Marx e Engels', 'Max Weber']::text[]),
('Sociologia', 'Cultura e Identidade', ARRAY[]::text[]),
('Sociologia', 'Instituições Sociais', ARRAY[]::text[]),
('Sociologia', 'Sociologia do Trabalho', ARRAY[]::text[]),
('Sociologia', 'Política', ARRAY[]::text[]),
('Sociologia', 'Movimentos Sociais', ARRAY['Abolição, racismo e antirracismo', 'Movimento feminista', 'Movimento LGBT', 'Movimento operário']::text[]),
('Sociologia', 'Sociologia Brasileira', ARRAY[]::text[]),
('Sociologia', 'Tecnologia', ARRAY[]::text[]),
('Sociologia', 'Religião', ARRAY[]::text[]),
('Sociologia', 'Indústria Cultural, Consumo, Comunicação e Influência', ARRAY[]::text[]),
('Sociologia', 'Consciência Coletiva', ARRAY[]::text[]),
('Biologia', 'Fundamentos da Biologia', ARRAY['Introdução à Célula', 'Níveis de Organização Biológica', 'Noções de Metabolismo e Energia', 'O que é Vida']::text[]),
('Biologia', 'Método Científico', ARRAY[]::text[]),
('Biologia', 'Bioquímica', ARRAY['Enzimas', 'Macromoléculas', 'Vitaminas']::text[]),
('Biologia', 'Citologia e Moléculas da Vida', ARRAY['Células', 'Divisão celular', 'Membrana Plasmática', 'Organelas', 'Transportes de membrana']::text[]),
('Biologia', 'Metabolismo Energético I', ARRAY['Fermentação', 'Respiração celular']::text[]),
('Biologia', 'Metabolismo Energético II', ARRAY['Fotossíntese', 'Quimiossíntese']::text[]),
('Biologia', 'Biologia Molecular', ARRAY['Bases nitrogenadas', 'DNA e RNA', 'Proteínas']::text[]),
('Biologia', 'Evolução e Classificação dos Seres Vivos', ARRAY['Cladogramas', 'Especiação', 'Origem da vida', 'Teorias evolutivas']::text[]),
('Biologia', 'Ecologia', ARRAY['Biomas e diversidade', 'Cadeia alimentar', 'Ciclos biogeoquímicos', 'Dinâmica de populações', 'Ecossistemas', 'Fluxos de energia e de matéria', 'Gráficos de relações ecológicas', 'Impactos antrópicos', 'Preservação e conservação ambiental', 'Problemas ambientais', 'Relações ecológicas', 'Sucessão ecológica']::text[]),
('Biologia', 'Impactos e Problemas Ambientais', ARRAY[]::text[]),
('Biologia', 'Genética', ARRAY['1° Lei de Mendel', '2° Lei de Mendel', 'Biotecnologia', 'Doenças genéticas', 'Engenharia genética', 'Fator Rh e Sistema ABO', 'Fundamentos da genética', 'Heredogramas', 'Interações gênicas']::text[]),
('Biologia', 'Histologia', ARRAY['Tecido Muscular']::text[]),
('Biologia', 'Fisiologia Humana', ARRAY['Sistema cardiorrespiratório', 'Sistema digestório', 'Sistema endócrino', 'Sistema excretor', 'Sistema hematopoietico', 'Sistema imunológico', 'Sistema nervoso', 'Sistema reprodutor']::text[]),
('Biologia', 'Botânica', ARRAY['Fisiologia vegetal', 'Fitormônios', 'Grupos vegetais', 'Histologia vegetal', 'Reprodução']::text[]),
('Biologia', 'Zoologia', ARRAY['Artrópodes e Equinodermos', 'Cordados', 'Primeiros filos']::text[]),
('Biologia', 'Doenças', ARRAY['Bacterioses', 'Protozooses e verminoses', 'Vírus e viroses']::text[]),
('Biologia', 'Microbiologia', ARRAY[]::text[]),
('Biologia', 'Reprodução e Embriologia', ARRAY[]::text[]),
('Física', 'Energia e suas Transformações', ARRAY['Fontes de energia', 'Impactos Ambientais e Contexto Energético']::text[]),
('Física', 'Ferramental Matemático', ARRAY['Conversão de unidades', 'Potência de 10 e notação científica', 'Proporção entre grandezas físicas', 'Triângulo retângulo na Física']::text[]),
('Física', 'Grandezas Físicas', ARRAY[]::text[]),
('Física', 'Termologia I', ARRAY['Calorimetria', 'Dilatação', 'Termometria']::text[]),
('Física', 'Cinemática I', ARRAY['Fundamentos da cinemática', 'Movimento uniforme', 'Movimento uniformemente variado', 'Queda livre e lançamento vertical']::text[]),
('Física', 'Ondulatória I', ARRAY['Espectro eletromagnético', 'Fenômenos ondulatórios', 'Propriedades das ondas']::text[]),
('Física', 'Dinâmica I', ARRAY['Força de atrito', 'Força elástica e lei de Hooke', 'Forças particulares', 'Leis de Newton', 'Polias fixas e móveis']::text[]),
('Física', 'Vetores', ARRAY[]::text[]),
('Física', 'Eletrostática', ARRAY['Campo e potencial elétrico', 'Eletrização', 'Força elétrica']::text[]),
('Física', 'Eletrodinâmica I', ARRAY['1º Lei de Ohm', '2º Lei de Ohm', 'Amperímetro e voltímetro', 'Circuitos elétricos', 'Potência elétrica', 'Tensão e corrente']::text[]),
('Física', 'Potência e Eficiência', ARRAY[]::text[]),
('Física', 'Cinemática II', ARRAY['Acoplamento no MCU', 'Cinemática vetorial', 'Lançamento horizontal', 'Lançamento oblíquo', 'Movimento circular']::text[]),
('Física', 'Termologia II', ARRAY['Gases', 'Termodinâmica']::text[]),
('Física', 'Dinâmica II', ARRAY['Dinâmica do MCU', 'Plano inclinado']::text[]),
('Física', 'Dinâmica III', ARRAY['Colisões', 'Energia cinética e mecânica', 'Energia potencial elástica', 'Energia potencial gravitacional', 'Força elástica', 'Impulso e quantidade de movimento', 'Movimento Harmônico Simples']::text[]),
('Física', 'Estática', ARRAY['Equilíbrio de corpos']::text[]),
('Física', 'Hidrostática', ARRAY['Densidade', 'Empuxo', 'Pressão']::text[]),
('Física', 'Eletrodinâmica II', ARRAY['Associação de pilhas e baterias', 'Geradores, receptores e capacitores', 'Ponte de Wheatstone']::text[]),
('Física', 'Magnetismo e Eletromagnetismo', ARRAY[]::text[]),
('Física', 'Óptica', ARRAY['Espelhos', 'Fenômenos ópticos', 'Lentes']::text[]),
('Física', 'Ondulatória II', ARRAY['Acústica']::text[]),
('Física', 'Gravitação', ARRAY[]::text[]),
('Física', 'Física Moderna', ARRAY['Física nuclear', 'Mecânica quântica', 'Radiação de corpo negro', 'Relatividade']::text[]),
('Química', 'Propriedades da Matéria', ARRAY[]::text[]),
('Química', 'Processos de Separação de Misturas', ARRAY[]::text[]),
('Química', 'Atomística', ARRAY['Alotropia', 'Efeitos luminosos', 'Leis ponderais', 'Modelo atômico atual', 'Modelos atômicos', 'Propriedades atômicas']::text[]),
('Química', 'Estequiometria', ARRAY['Cálculos estequiométricos', 'Variáveis no cálculo estequiométrico']::text[]),
('Química', 'Tabela Periódica e suas Propriedades', ARRAY['Elementos químicos', 'Famílias e períodos', 'Propriedades periódicas']::text[]),
('Química', 'Química Orgânica', ARRAY['Compostos orgânicos', 'Funções orgânicas', 'Isomeria', 'Reações orgânicas']::text[]),
('Química', 'Ligações Químicas, Propriedades dos Compostos e Polaridade', ARRAY['Forças intermoleculares', 'Ligações químicas', 'Polaridade']::text[]),
('Química', 'Geometria Molecular', ARRAY['Arranjos geométricos espaciais', 'Teoria da Repulsão dos Pares de Elétrons']::text[]),
('Química', 'Radioatividade', ARRAY['Decaimento radioativo', 'Partículas', 'Reações nucleares']::text[]),
('Química', 'Propriedades Coligativas', ARRAY['Crioscopia', 'Osmoscopia', 'Tonoscopia']::text[]),
('Química', 'Eletroquímica', ARRAY['Eletrólise', 'Oxirredução', 'Pilhas', 'Reações']::text[]),
('Química', 'Química Ambiental', ARRAY[]::text[]),
('Química', 'Química Inorgânica', ARRAY['Ácidos', 'Bases', 'Funções inorgânicas', 'Ionização e dissociação iônica', 'NOX', 'Óxidos', 'Reações inorgânicas', 'Sais']::text[]),
('Química', 'Termoquímica', ARRAY['Equações termoquímicas', 'Lei de Hess']::text[]),
('Química', 'Soluções', ARRAY['Concentração', 'Diluição e mistura de soluções', 'Dispersões']::text[]),
('Química', 'Equilíbrio Químico', ARRAY[]::text[]),
('Química', 'Cinética Química', ARRAY[]::text[]),
('Química', 'Reações Químicas', ARRAY[]::text[]),
('Química', 'Gases e suas Transformações', ARRAY[]::text[]),
('Química', 'Polímeros', ARRAY[]::text[]),
('Linguagens e Códigos', 'Funções da Linguagem', ARRAY[]::text[]),
('Linguagens e Códigos', 'Figuras de Linguagem', ARRAY[]::text[]),
('Linguagens e Códigos', 'Tipologias Textuais', ARRAY[]::text[]),
('Linguagens e Códigos', 'Gêneros Textuais', ARRAY[]::text[]),
('Linguagens e Códigos', 'Campanhas Publicitárias, Anúncios e Influência', ARRAY[]::text[]),
('Linguagens e Códigos', 'Crítica Social, Cultural e Artística', ARRAY[]::text[]),
('Linguagens e Códigos', 'Variações Linguísticas', ARRAY['Normas linguísticas', 'Patrimônio linguístico']::text[]),
('Linguagens e Códigos', 'Poemas e Poesias', ARRAY[]::text[]),
('Linguagens e Códigos', 'Expressividade e Lirismo', ARRAY[]::text[]),
('Linguagens e Códigos', 'Progressão Textual e Temática', ARRAY[]::text[]),
('Linguagens e Códigos', 'Mecanismos de Coesão e Coerência', ARRAY[]::text[]),
('Linguagens e Códigos', 'Intertextualidade', ARRAY[]::text[]),
('Linguagens e Códigos', 'Charges e HQs', ARRAY[]::text[]),
('Linguagens e Códigos', 'Literatura', ARRAY['Arcadismo', 'Barroco', 'Classicismo', 'Contemporânea', 'Leituras obrigatórias', 'Modernismo', 'Naturalismo', 'Parnasianismo', 'Quinhentismo', 'Realismo', 'Romantismo', 'Simbolismo', 'Trovadorismo']::text[]),
('Linguagens e Códigos', 'Artes', ARRAY['Cubismo', 'Dadaísmo', 'Expressionismo', 'Futurismo', 'Surrealismo']::text[]),
('Linguagens e Códigos', 'Movimentos Artísticos', ARRAY[]::text[]),
('Linguagens e Códigos', 'Recursos Argumentativos', ARRAY[]::text[]),
('Linguagens e Códigos', 'Estratégias Argumentativas', ARRAY[]::text[]),
('Linguagens e Códigos', 'Gramática', ARRAY['Colocação Pronominal', 'Concordância', 'Fonética e Fonologia', 'Morfologia', 'Ortografia e Acentuação', 'Pontuação', 'Regência', 'Semântica e Lexicologia', 'Sintaxe']::text[]),
('Linguagens e Códigos', 'Tecnologias', ARRAY[]::text[]),
('Linguagens e Códigos', 'Interpretação de Texto', ARRAY[]::text[]),
('Linguagens e Códigos', 'Educação Física', ARRAY[]::text[]),
('Linguagens e Códigos', 'Linguagem Corporal', ARRAY[]::text[]),
('Espanhol', 'Interpretação de Texto', ARRAY[]::text[]),
('Espanhol', 'Charges e HQ''s', ARRAY[]::text[]),
('Espanhol', 'Campanhas Publicitárias', ARRAY[]::text[]),
('Espanhol', 'Vocabulário e Semântica', ARRAY[]::text[]),
('Inglês', 'Vocabulário e Semântica', ARRAY[]::text[]),
('Inglês', 'Interpretação de Texto', ARRAY[]::text[]),
('Inglês', 'Charges e HQs', ARRAY[]::text[]),
('Inglês', 'Campanhas Publicitárias', ARRAY[]::text[]),
('Matemática', 'Fundamentos da Matemática', ARRAY['Divisão', 'Frações', 'Multiplicação', 'Potenciação', 'Radiciação', 'Soma', 'Subtração']::text[]),
('Matemática', 'Razão, Proporção e Regra de Três', ARRAY['Divisão diretamente proporcional', 'Divisão inversamente proporcional', 'Regra de 3 composta', 'Regra de 3 simples']::text[]),
('Matemática', 'Razão e Proporção Avançada', ARRAY['Regra de 3 simples']::text[]),
('Matemática', 'Porcentagem', ARRAY['Aumento percentual', 'Redução percentual', 'Taxa percentual']::text[]),
('Matemática', 'Unidades de Medida e Conversões', ARRAY[]::text[]),
('Matemática', 'Notação Cientifica', ARRAY[]::text[]),
('Matemática', 'Escalas', ARRAY['Escalas lineares', 'Escalas superficiais', 'Escalas volumétricas']::text[]),
('Matemática', 'Vazão', ARRAY[]::text[]),
('Matemática', 'Matemática Financeira', ARRAY['Aumentos', 'Descontos', 'Juros compostos', 'Juros Simples', 'Taxa percentual']::text[]),
('Matemática', 'Gráficos e Tabelas', ARRAY['Gráficos', 'Tabelas']::text[]),
('Matemática', 'Estatística', ARRAY['Desvio padrão e variância', 'Medidas de tendência central']::text[]),
('Matemática', 'Conjuntos', ARRAY[]::text[]),
('Matemática', 'Álgebra', ARRAY['Números complexos', 'Polinômios']::text[]),
('Matemática', 'Inequações', ARRAY[]::text[]),
('Matemática', 'Sistemas e Equações', ARRAY['Escalonamento', 'Primeiro grau', 'Segundo grau']::text[]),
('Matemática', 'Função do Primeiro Grau', ARRAY[]::text[]),
('Matemática', 'Progressão Aritmética', ARRAY['Soma dos termos', 'Termo geral']::text[]),
('Matemática', 'Sequências Lógicas', ARRAY[]::text[]),
('Matemática', 'Progressão Geométrica', ARRAY[]::text[]),
('Matemática', 'Função do Segundo Grau', ARRAY[]::text[]),
('Matemática', 'Geometria Plana', ARRAY['Ângulos', 'Área e perímetro', 'Circunferências e arcos', 'Polígonos e semelhança', 'Razões trigonométricas']::text[]),
('Matemática', 'Trigonometria', ARRAY[]::text[]),
('Matemática', 'Geometria Espacial', ARRAY['Poliedros', 'Projeção ortogonal']::text[]),
('Matemática', 'Geometria Analítica', ARRAY['Circunferência', 'Plano cartesiano', 'Reta']::text[]),
('Matemática', 'Análise Combinatória', ARRAY['Arranjo', 'Combinação', 'Permutação', 'PFC']::text[]),
('Matemática', 'Probabilidade', ARRAY[]::text[]),
('Matemática', 'Função Exponencial e Logarítmica', ARRAY[]::text[]),
('Matemática', 'Função Trigonométrica', ARRAY[]::text[]),
('Matemática', 'Logaritmo', ARRAY[]::text[]),
('Matemática', 'Matrizes', ARRAY[]::text[]),
('Matemática', 'Lógica', ARRAY[]::text[]),
('Matemática', 'MMC e MDC', ARRAY[]::text[]),
('Matemática', 'Conjuntos Numéricos', ARRAY[]::text[]),
('Matemática', 'Função Racional', ARRAY[]::text[]),
('Redação', 'Cadernos de Aprimoramento Textual', ARRAY[]::text[]),
('Intensivo Revisional', 'Matemática', ARRAY[]::text[]),
('Intensivo Revisional', 'Biologia', ARRAY[]::text[]),
('Intensivo Revisional', 'Química', ARRAY[]::text[]),
('Intensivo Revisional', 'Física', ARRAY[]::text[])
on conflict (disciplina, topico) do update set assuntos = excluded.assuntos;
